
import React from 'react';
import { MoodConfig } from './types';

export const MOODS: MoodConfig[] = [
  { id: 'happy', labelEn: 'Feel Good', labelKn: 'ಖುಷಿ', icon: '😊', genres: [35, 10751, 12] },
  { id: 'sad', labelEn: 'Emotional', labelKn: 'ಭಾವನಾತ್ಮಕ', icon: '😢', genres: [18, 10749] },
  { id: 'thriller', labelEn: 'Adrenaline', labelKn: 'ಉತ್ಸಾಹ', icon: '⚡', genres: [53, 27, 80] },
  { id: 'romantic', labelEn: 'Romantic', labelKn: 'ಪ್ರೇಮ', icon: '❤️', genres: [10749, 18] },
  { id: 'action', labelEn: 'Action Packed', labelKn: 'ಸಾಹಸ', icon: '💥', genres: [28, 12, 878] }
];

export const GENRES: Record<number, string> = {
  28: 'Action',
  12: 'Adventure',
  16: 'Animation',
  35: 'Comedy',
  80: 'Crime',
  99: 'Documentary',
  18: 'Drama',
  10751: 'Family',
  14: 'Fantasy',
  36: 'History',
  27: 'Horror',
  10402: 'Music',
  9648: 'Mystery',
  10749: 'Romance',
  878: 'Science Fiction',
  10770: 'TV Movie',
  53: 'Thriller',
  10752: 'War',
  37: 'Western'
};

export const TRANSLATIONS: Record<string, any> = {
  en: {
    welcome: "Welcome to ChalaChitra",
    tagline: "Your Intelligent Movie Companion",
    searchPlaceholder: "Search movies, actors, or moods...",
    priorityLanguage: "Priority Language",
    priorityContent: "Priority Content",
    trending: "Trending Now",
    recommendations: "Recommended for You",
    moods: "Choose your mood",
    voiceSearch: "Voice Search",
    chatAssistant: "ChalaChitra Assistant",
    hiddenGems: "Hidden Gems",
    weekendSpecial: "Weekend Watch",
    settings: "Settings",
    adminDashboard: "Admin Panel",
    logout: "Logout",
    login: "Login",
    register: "Register",
    tmdbKeyMissing: "Please update your access token in Settings to synchronize movie data.",
    showAll: "Show All",
    relatedMovies: "Related Movies",
    whereToWatch: "Where to Watch",
    streaming: "Streaming",
    rent: "Rent",
    buy: "Buy",
    notAvailable: "Not available on digital platforms in your region.",
    poweredBy: "Powered by JustWatch",
    mainCast: "Main Cast",
    theTeam: "The Acting Team",
    curatedRecommendations: "Curated Recommendations",
    priorityDesc: "Boost movies from this language in your feed.",
    kannadaMovies: "Kannada Movies",
    teluguMovies: "Telugu Movies",
    hindiMovies: "Hindi Movies",
    malayalamMovies: "Malayalam Movies",
    blockbusters2020: "2020-2025 Blockbusters"
  },
  kn: {
    welcome: "ಸಿನಿಮಾ ಮಿತ್ರಕ್ಕೆ ಸ್ವಾಗತ",
    tagline: "ನಿಮ್ಮ ಬುದ್ಧಿವಂತ ಚಲನಚಿತ್ರ ಸಂಗಾತಿ",
    searchPlaceholder: "ಚಿತ್ರಗಳು, ನಟರು ಅಥವಾ ಮೂಡ್‌ಗಳನ್ನು ಹುಡುಕಿ...",
    priorityLanguage: "ಆದ್ಯತೆಯ ಭಾಷೆ",
    priorityContent: "ಆದ್ಯತೆಯ ಚಿತ್ರಗಳು",
    trending: "ಈಗ ಪ್ರಚಲಿತದಲ್ಲಿರುವವು",
    recommendations: "ನಿಮಗಾಗಿ ಶಿಫಾರಸುಗಳು",
    moods: "ಇಂದು ನಿಮ್ಮ ಮೂಡ್ ಹೇಗಿದೆ?",
    voiceSearch: "ಧ್ವನಿ ಹುಡುಕಾಟ",
    chatAssistant: "ಮಿತ್ರ ಅಸಿಸ್ಟೆಂಟ್",
    hiddenGems: "ಅಪರೂಪದ ರತ್ನಗಳು",
    weekendSpecial: "ವಾರಾಂತ್ಯದ ವಿಶೇಷ",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    adminDashboard: "ಅಡ್ಮಿನ್ ಪ್ಯಾನಲ್",
    logout: "ನಿರ್ಗಮಿಸಿ",
    login: "ಲಾಗಿನ್",
    register: "ನೋಂದಣಿ",
    tmdbKeyMissing: "ಚಲನಚಿತ್ರ ಡೇಟಾವನ್ನು ಸಿಂಕ್ರೊನೈಸ್ ಮಾಡಲು ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ನಿಮ್ಮ ಪ್ರವೇಶ ಟೋಕನ್ ಅನ್ನು ನವೀಕರಿಸಿ.",
    showAll: "ಎಲ್ಲವನ್ನೂ ನೋಡಿ",
    relatedMovies: "ಸಂಬಂಧಿತ ಚಿತ್ರಗಳು",
    whereToWatch: "ಎಲ್ಲಿ ವೀಕ್ಷಿಸಬೇಕು?",
    streaming: "ಸ್ಟ್ರೀಮಿಂಗ್",
    rent: "ಬಾಡಿಗೆ",
    buy: "ಖರೀದಿ",
    notAvailable: "ನಿಮ್ಮ ಪ್ರದೇಶದ ಡಿಜಿಟಲ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗಳಲ್ಲಿ ಲಭ್ಯವಿಲ್ಲ.",
    poweredBy: "JustWatch ಇಂದ ಲಭ್ಯ",
    mainCast: "ಮುಖ್ಯ ಪಾತ್ರವರ್ಗ",
    theTeam: "ಅಭಿನಯ ತಂಡ",
    curatedRecommendations: "ವಿಶೇಷ ಶಿಫಾರಸುಗಳು",
    priorityDesc: "ನಿಮ್ಮ ಫೀಡ್‌ನಲ್ಲಿ ಈ ಭಾಷೆಯ ಚಿತ್ರಗಳಿಗೆ ಆದ್ಯತೆ ನೀಡಿ.",
    kannadaMovies: "ಕನ್ನಡ ಚಿತ್ರಗಳು",
    teluguMovies: "ತೆಲುಗು ಚಿತ್ರಗಳು",
    hindiMovies: "ಹಿಂದಿ ಚಿತ್ರಗಳು",
    malayalamMovies: "ಮಲಯಾಳಂ ಚಿತ್ರಗಳು",
    blockbusters2020: "2020-2025 ಬ್ಲಾಕ್‌ಬಸ್ಟರ್‌ಗಳು"
  },
  hi: {
    welcome: "सिनेमा मित्र में आपका स्वागत है",
    tagline: "आपका बुद्धिमान मूवी साथी",
    searchPlaceholder: "फिल्में, अभिनेता या मूड खोजें...",
    priorityLanguage: "प्राथमिकता भाषा",
    priorityContent: "प्राथमिकता सामग्री",
    trending: "ट्रेंडिंग",
    recommendations: "आपके लिए सिफारिशें",
    moods: "आज आपका मूड कैसा है?",
    voiceSearch: "वॉयस सर्च",
    chatAssistant: "मित्र सहायक",
    hiddenGems: "छिपे हुए रत्न",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    showAll: "सभी दिखाएं",
    whereToWatch: "कहाँ देखें",
    streaming: "स्ट्रीमिंग",
    tmdbKeyMissing: "मूवी डेटा सिंक करने के लिए सेटिंग्स में अपना एक्सेस टोकन अपडेट करें।"
  },
  te: {
    welcome: "సినిమా మిత్రకు స్వాగతం",
    tagline: "మీ తెలివైన మూవీ తోడు",
    searchPlaceholder: "సినిమాలు, నటులు లేదా మూడ్స్ వెతకండి...",
    priorityLanguage: "ప్రాధాన్యత భాష",
    priorityContent: "ప్రాధాన్యత కంటెంట్",
    trending: "ట్రెండింగ్",
    recommendations: "మీ కోసం సిఫార్సులు",
    moods: "ఈరోజు మీ మూడ్ ఎలా ఉంది?",
    voiceSearch: "వాయిస్ సెర్చ్",
    chatAssistant: "మిత్ర అసిస్టెంట్",
    settings: "సెట్టింగ్స్",
    logout: "లాగ్ అవుట్",
    showAll: "అన్నీ చూడండి",
    whereToWatch: "ఎక్కడ చూడాలి",
    tmdbKeyMissing: "డేటాను సింక్ చేయడానికి సెట్టింగ్స్‌లో మీ యాక్సెస్ టోకెన్ను అప్‌డేట్ చేయండి."
  },
  ta: {
    welcome: "சினிமா மித்ராவிற்கு வரவேற்கிறோம்",
    tagline: "உங்கள் அறிவார்ந்த திரைப்படத் துணை",
    searchPlaceholder: "திரைப்படங்கள், நடிகர்கள் அல்லது மனநிலையைத் தேடுங்கள்...",
    priorityLanguage: "முன்னுரிமை மொழி",
    priorityContent: "முன்னுரிமை உள்ளடக்கம்",
    trending: "பிரபலமானவை",
    recommendations: "உங்களுக்கான பரிந்துரைகள்",
    moods: "இன்று உங்கள் மனநிலை எப்படி இருக்கிறது?",
    voiceSearch: "குரல் தேடல்",
    chatAssistant: "மித்ரா உதவியாளர்",
    settings: "அமைப்புகள்",
    logout: "வெளியேறு",
    showAll: "அனைத்தையும் காட்டு",
    whereToWatch: "எங்கே பார்ப்பது",
    tmdbKeyMissing: "தரவை ஒத்திசைக்க அமைப்புகளில் உங்கள் அணுகல் டோக்கனைப் புதுப்பிக்கவும்."
  },
  ml: {
    welcome: "സിനിമ മിത്രയിലേക്ക് സ്വാഗതം",
    tagline: "നിങ്ങളുടെ ബുദ്ധിയുള്ള സിനിമ കൂട്ടുകാരൻ",
    searchPlaceholder: "സിനിമകൾ, നടന്മാർ അല്ലെങ്കിൽ മൂഡുകൾ തിരയുക...",
    priorityLanguage: "മുൻഗണനാ ഭാഷ",
    priorityContent: "മുൻഗണനാ ഉള്ളടക്കം",
    trending: "ട്രെൻഡിംഗ്",
    recommendations: "നിങ്ങൾക്കായി ശുപാർശ ചെയ്യുന്നവ",
    moods: "ഇന്ന് നിങ്ങളുടെ മൂഡ് എങ്ങനെയുണ്ട്?",
    voiceSearch: "വോയ്‌സ് സെർച്ച്",
    chatAssistant: "മിത്ര അസിസ്റ്റന്റ്",
    settings: "ക്രമീകരണങ്ങൾ",
    logout: "ലോഗ് ഔട്ട്",
    showAll: "എല്ലാം കാണുക",
    whereToWatch: "എവിടെ കാണണം",
    tmdbKeyMissing: "ഡാറ്റ സമന്വയിപ്പിക്കാൻ ക്രമീകരണങ്ങളിൽ നിങ്ങളുടെ ആക്സസ് ടോക്കൺ പുതുക്കുക."
  },
  bn: {
    welcome: "সিনেমা মিত্র-তে স্বাগতম",
    tagline: "আপনার বুদ্ধিমান মুভি সঙ্গী",
    searchPlaceholder: "সিনেমা, অভিনেতা বা মুড খুঁজুন...",
    priorityLanguage: "অগ্রাধিকার ভাষা",
    priorityContent: "অগ্রাধিকার কন্টেন্ট",
    trending: "ট্রেন্ডিং",
    recommendations: "আপনার জন্য সুপারিশ",
    moods: "আজ আপনার মুড কেমন?",
    voiceSearch: "ভয়েস সার্চ",
    chatAssistant: "মিত্র সহকারী",
    settings: "সেটিংস",
    logout: "লগআউট",
    showAll: "সব দেখুন",
    whereToWatch: "কোথায় দেখবেন",
    tmdbKeyMissing: "মুভি ডেটা সিঙ্ক করতে সেটিংসে আপনার অ্যাক্সেস টোকেন আপডেট করুন।"
  },
  mr: {
    welcome: "सिनेมา मित्र मध्ये आपले स्वागत आहे",
    tagline: "तुमचा बुद्धिमान चित्रपट सोबती",
    searchPlaceholder: "चित्रपट, कलाकार किंवा मूड शोधा...",
    priorityLanguage: "प्राधान्य भाषा",
    priorityContent: "प्राधान्य सामग्री",
    trending: "ट्रेंडिंग",
    recommendations: "तुमच्यासाठी शिफारसी",
    moods: "आज तुमचा मूड कसा आहे?",
    voiceSearch: "व्हॉइस सर्च",
    chatAssistant: "मित्र सहाय्यक",
    settings: "सेटिंग्ज",
    logout: "लॉगआउट",
    showAll: "सर्व पहा",
    whereToWatch: "कुठे पाहायचे",
    tmdbKeyMissing: "डेटा सिंक करण्यासाठी सेटिंग्जमध्ये तुमचा प्रवेश टोकन अपडेट करा।"
  },
  ja: {
    welcome: "シネマ・ミスラへようこそ",
    tagline: "あなたのインテリジェントな映画コンパニオン",
    searchPlaceholder: "映画、俳優、気分を検索...",
    priorityLanguage: "優先言語",
    priorityContent: "優先コンテンツ",
    trending: "今注目の作品",
    recommendations: "あなたへのおすすめ",
    moods: "今日の気分は？",
    voiceSearch: "音声検索",
    chatAssistant: "ミスラ・アシスタント",
    settings: "設定",
    logout: "ログアウト",
    showAll: "すべて表示",
    whereToWatch: "視聴場所",
    tmdbKeyMissing: "データを同期するには、設定でアクセストークンを更新してください。"
  },
  ko: {
    welcome: "시네마 미스라에 오신 것을 환영합니다",
    tagline: "당신의 지능형 영화 동반자",
    searchPlaceholder: "영화, 배우 또는 분위기 검색...",
    priorityLanguage: "우선 언어",
    priorityContent: "우선 콘텐츠",
    trending: "지금 트렌드",
    recommendations: "당신을 위한 추천",
    moods: "오늘 기분은 어떠신가요?",
    voiceSearch: "음성 검색",
    chatAssistant: "미스라 어시스턴트",
    settings: "설정",
    logout: "로그아웃",
    showAll: "모두 보기",
    whereToWatch: "시청할 수 있는 곳",
    tmdbKeyMissing: "데이터를 동기화하려면 설정에서 액세스 토큰을 업데이트하세요."
  }
};
